### ISSUE TITLE
Change icon when menu sticks.

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/wst-wp-theme#1]
Please, a small change @good4work, when the menu sticks, the logo goes to the menu bar.
Use this logo on menu bar http://blog.welcomesurftrips.com.br/wp-content/uploads/sites/7/2015/08/LogoWST_Flat03.png

**Comment by good4work** [comment]
Done

**Comment by edpichler** [comment]
@good4work could you attach a print here?

**Comment by good4work** [comment]
![fireshot](https://cloud.githubusercontent.com/assets/2932403/9440992/34cf4cb6-4a95-11e5-9def-2532b696b0db.png)

Please check.

**Comment by edpichler** [comment]
But is it on localhosh?

On Mon, Aug 24, 2015 at 10:21 AM, saif notifications@github.com wrote:

> [image: fireshot]
> https://cloud.githubusercontent.com/assets/2932403/9440992/34cf4cb6-4a95-11e5-9def-2532b696b0db.png
> 
> Please check.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/welcome-surf-trips/wst-wp-theme/issues/1#issuecomment-134199154
> .

## 

"Onde cruzam seus talentos e paixões com as necessidades do mundo, lá
estará o seu lugar"

```
              Aristóteles
```
